### ISSUE TITLE
list_checker.rb colour refs

### ISSUE THREAD

**Issue by WebBreacher** [digininja/pipal#25]
It looks like you pulled the colour checking class out from list_checker.rb but there are still variable references/names in that file referencing the colour variables. 

For instance, the following excerpt shows the "colour" variables. Should they be more generically named now?

```
def process_word (word, extras = nil)
		@list.each_pair do |colour, count|
			if /#{colour}/i.match word
				@list[colour] += 1
```

**Comment by digininja** [comment]
Ye, I spotted that but have been to lazy to fix it, will sort it.

**Comment by WebBreacher** [comment]
No worries. I like pipal a bunch and have started using it more. Trying to understand its flow and calls and such.

**Comment by digininja** [comment]
Fixed this
