### ISSUE TITLE
unknown regexp option s - bac (SyntaxError)

### ISSUE THREAD

**Issue by truekonrads** [digininja/pipal#37]
```C:\Tools\pipal>ruby pipal.rb
C:/Tools/Coding/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:i
n `require': C:/Tools/pipal/checkers_enabled/01basic.rb:1: unknown regexp option
s - bac (SyntaxError)
        from C:/Tools/Coding/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_re
quire.rb:36:in `require'
        from pipal.rb:184:in `block in <main>'
        from pipal.rb:179:in `each'
        from pipal.rb:179:in `<main>'
```

**Comment by digininja** [comment]
Can you give me a bit more to work on. What version are you using? How did you run the app? What command line options did you give?

Can you try it with an up-to-date version of Ruby? 1.9.1 hasn't been supported for at least a couple of years.

**Comment by truekonrads** [comment]
I used a current from github. But check out the 
https://github.com/digininja/pipal/blob/master/checkers_enabled/01basic.rb, the contents right now are:

```
../checkers_available/basic.rb
```
And I'm certain this isn't a valid syntax

**Comment by digininja** [comment]
That is a Linux symlink, to run in windows you have to copy the files from
available to enabled.

**Comment by truekonrads** [comment]
OK, so the bug is - doesn't work on Windows :)

**Comment by digininja** [comment]
Ye.

I might add something to the readme about running it on windows but I don't
think the user base is big enough to put any serious effort into getting a
cross platform solution for this one file.

**Comment by h3xstream** [comment]
See #41 to see on to use pipal on Windows

**Comment by digininja** [comment]
Give it a go and see if it works for you.

**Comment by h3xstream** [comment]
@truekonrads Ping
