### ISSUE TITLE
Change branding/wording

### ISSUE THREAD

**Issue by WebBreacher** [digininja/pipal#38]
This tool is really a string analyzer. Most of the time, people pass passwords to it to analyze. But you can pass any word list to it. I suggest changing all the output and help text to move from "password" to "string" to help people understand it can be used in wider cases.

**Comment by digininja** [comment]
If I manage the re-release with the rewrite then I'll change the branding then.

**Comment by h3xstream** [comment]
🤔 And then.. hashcat and jtr are not password cracker, but string cracker.
I would not worry about the wording to much.
