### ISSUE TITLE
Masks

### ISSUE THREAD

**Issue by plaverty9-r7** [digininja/pipal#43]
Pipal is my go-to password analyzer. Love it. The one additional thing I wish it had is the hashcat mask generator that PACK has. I always run both analyzers, but PACK just to get the masks. If pipal had that, that would be pretty awesome. I thought of just merging the two, but PACK is python and pipal is ruby. I've never tried ruby myself, otherwise I'd jump in and try to create a version myself. Sorry...

Here is the source code for PACK: https://thesprawl.org/projects/pack/

**Comment by digininja** [comment]
Never heard of PACK but will have a look, shouldn't be too hard to do.

**Comment by plaverty9-r7** [comment]
Thanks! Here is a sample output, where the number at the end is the number of passwords matching that mask. 

[+]        ?u?l?l?l?l?l?l?l?d: 08% (231)
[+]    ?s?u?l?l?l?s?u?l?l?l?d: 07% (197)
[+]          ?u?l?l?l?l?d?d?d: 07% (192)
[+]        ?u?l?l?l?l?d?d?d?d: 04% (109)
[+]          ?u?l?l?l?l?l?l?d: 03% (80)
[+]          ?u?l?l?l?l?l?d?d: 02% (74)
[+]          ?u?l?l?l?d?d?d?d: 02% (60)
[+]      ?u?l?l?l?l?l?d?d?d?d: 02% (60)

**Comment by digininja** [comment]
Is this the type of output you are after?

```
Hashcat masks (Top 10)

?l?l?l: 1 (20.0%)
?d?d?d: 1 (20.0%)
?l?l?l?d?d?d: 1 (20.0%)
?l?l?l?l?l?l?l?d?l?l?l?d?d?d?l?l?l?l?l?l?l?l?l?l?l?l?l?l: 1 (20.0%)
?d?d?d?l?l?l?l?d?d?d: 1 (20.0%)
```

**Comment by plaverty9-r7** [comment]
Yep! That looks great! Thanks!

**Comment by digininja** [comment]
In which case, it's been there all the time! Enable the
hashcat_mask_generator.rb.

**Comment by plaverty9-r7** [comment]
<kick>

Thank you, sir! As always, you're the best!
