### ISSUE TITLE
Running a Batch

### ISSUE THREAD

**Issue by Mdetrinidad** [digininja/pipal#46]

**Comment by Mdetrinidad** [comment]
When trying to run several files to analyze in a batch script I get a "Can't find password file".  This happens when the files are in the same directory as pipal or in other directories.  Also running  as root as well.   But if I run the command manually for the same files one at a time it works fine.  Any ideas as to what I am doing wrong?

_**root@kali:~/pipal# ./pipal.sh
pipal 3.1 Robin Wood (robin@digi.ninja) (http://digi.ninja)
Can't find the password file**_

**Comment by digininja** [comment]
I don't know what version you are using as I don't have a .sh script.

Use the latest version from the repo and see if that does what you need.

**Comment by monsterpython** [comment]
pipal 3.1 Robin Wood (robin@digi.ninja) (http://digi.ninja)
Can't find the password file 
please fix this issue

**Comment by digininja** [comment]
See my previous response.
