### ISSUE TITLE
syntax error ?!!!

### ISSUE THREAD

**Issue by nrxsh** [digininja/pipal#48]
i had tried ruby1.9.3 and higher versoin and got same error
`[root@localhost pipal-master]# ./pipal.ry -?
-bash: ./pipal.ry: No such file or directory
[root@localhost pipal-master]# ./pipal.rb -?
<internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': /opt/pipal-master/checkers_enabled/01basic
.rb:1: unknown regexp options - bac (SyntaxError)
../checkers_available/basic.rb
                     ^~~~~~
        from <internal:/usr/local/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from ./pipal.rb:184:in `block in <main>'
        from ./pipal.rb:179:in `each'
        from ./pipal.rb:179:in `<main>'
[root@localhost pipal-master]#
`
how can i fix this?

**Comment by digininja** [comment]
I've just tested it with Ruby 3.0 and it is working fine for me so I'm guessing it is something in your environment.

What OS are you on?

Can you show a directory listing of the Pipal directory including the contents of checkers_enabled and checkers_available.

**Comment by xkeksi** [comment]
i have the same error, u wanna reopen this issue?

**Comment by digininja** [comment]
In which case, create a new ticket and please give more information,
including what I asked for originally.
