### ISSUE TITLE
Can't find password file

### ISSUE THREAD

**Issue by prakhar-mishra-hub** [digininja/pipal#49]
![pipal](https://user-images.githubusercontent.com/69792106/116083286-14525500-a6ba-11eb-9ba7-ca23bfd919ed.jpeg)

**Comment by digininja** [comment]
That looks like you are running a version that has been installed by the Kali package manager which I don't support, only installs directly from the GitHub source.

My guess would be that password.txt does not exist in that directory.

**Comment by prakhar-mishra-hub** [comment]
I am using the from GitHub source
![pipal2](https://user-images.githubusercontent.com/69792106/116085672-ac513e00-a6bc-11eb-8f44-8503d6bb2177.jpeg)

**Comment by digininja** [comment]
As the error says, password.txt does not exist in that directory so it can't find it.

**Comment by prakhar-mishra-hub** [comment]
Same error when using some other .txt name
![pipal123](https://user-images.githubusercontent.com/69792106/116087874-f1766f80-a6be-11eb-939d-c33436e1fa42.jpeg)

**Comment by digininja** [comment]
That is right, wordlist123.txt does not exist in that directory either.
