### ISSUE TITLE
Passing email ids [question]

### ISSUE THREAD

**Issue by Fifirex** [digininja/pipal#52]
I have a dump of cleartext email id and password pairs. I have used the basic checkers like `basic.rb`, `date_checker.rb`, etc. by extracting all passwords in a txt file and passing that. But I can't figure out how am I supposed to pass the email ids for using the `email_names.rb` file. I have tried passing the file as colon-separated lines of pairs but that doesn't seem to work...

The `--external` param (mentioned in the readme) is also removed.

Thanks!

**Comment by digininja** [comment]
You need to enable a custom splitter for this to work. Check out the spliters_available directory and there is a file pipe_pass_user.rb, symlink that to custom_splitter.rb in the root and when you pass in the file, have it in the format:

```
password|username
```

You can then able the usernames checker and it will have the names and the passwords.

```
cat /tmp/ptest 
robin1|robin
pass|word
password|password
abc|asdfasfd
```

```
./pipal.rb /tmp/ptest

Username Checker
================

Exact Matches
-------------
Total: 1 Unique

password

Levenshtein Results
-------------------
Average distance 3.0

Close Matches
-------------
Total: 1 Unique

D: 1 U: robin P: robin1
```

I don't now what happened to the `external` parameter, I'll look into that if I get chance.

**Comment by Fifirex** [comment]
This doesn't seem to work :/

![Screenshot 2021-11-03 at 7 11 45 PM](https://user-images.githubusercontent.com/75205458/140071056-62ded2bc-109d-4f9e-a79a-85bb0cc37c87.png)

I have stored the txt file in the format you mentioned 
```
email id|password
```

**Comment by Fifirex** [comment]
ah just realised its the other way round... will do this:
```
password|email id
```
Sorry :sweat_smile:

**Comment by digininja** [comment]
If you need it the other way round, just change the code in the splitter.
