### ISSUE TITLE
unknown regexp options - bac (SyntaxError)

### ISSUE THREAD

**Issue by xkeksi** [digininja/pipal#55]
So, i tried installing ruby on a new OS, Debian 11, Latest linux and on Windows

None of them did work and all throwing the same error

`root@20012-42031:~/test# ./pipal.rb --help
Traceback (most recent call last):
        4: from ./pipal.rb:179:in `<main>'
        3: from ./pipal.rb:179:in `each'
        2: from ./pipal.rb:184:in `block in <main>'
        1: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require': /root/test/checkers_enabled/01basic.rb:1: unknown regexp options - bac (SyntaxError)
../checkers_available/basic.rb`

ruby versions used:
windows (3.0)
debian (2.7)
linux (2.5)

**Comment by digininja** [comment]
On Windows it is unlikey to work due to symlinking not working.

I've just installed ruby 3.0 on Debian and it works fine.

```robin@Debian pipal $ ruby -v
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]
robin@Debian pipal $ ./pipal.rb --help
pipal 3.1.2 Robin Wood (robin@digi.ninja) (http://digi.ninja)

Usage: pipal [OPTION] ... FILENAME
        --help, -h, -?: show help
        --top, -t X: show the top X results (default 10)
        --output, -o <filename>: output to file
        --gkey <Google Maps API key>: to allow zip code lookups (optional)
        --list-checkers: Show the available checkers and which are enabled
        --verbose, -v: Verbose


        FILENAME: The file to count
```

Looking at the error I'd say it is also a symlink issue on the Linux boxes. What is the content of your checkers_enabled directory?

**Comment by xkeksi** [comment]
Well, i tried it to run on a private server (vps), and it works with every other tool expect pipal, my checkers_enabled dir is the default one from the repo.

I'm a programmer myself too and checked the src, it makes no sense that it throws anywhere a error

**Comment by digininja** [comment]
Can you show me the output of `ls -al` on your two checkers directories and
run `head` on all files in the enabled directory.

**Comment by xkeksi** [comment]
`total 24
drwxrwxrwx 2 root root 4096 Feb  5 13:03 .
drwxr-xr-x 6 root root 4096 Feb  5 13:03 ..
-rwxrwxrwx 1 root root   30 Aug 14 19:23 01basic.rb
-rwxrwxrwx 1 root root   40 Feb  5 12:47 01basic.rb.bak
-rw-r--r-- 1 root root   91 Aug 14 19:23 .gitignore
-rwxrwxrwx 1 root root  243 Aug 14 19:23 README`


`total 280
drwxrwxrwx 2 root root  4096 Feb  5 13:03 .
drwxr-xr-x 6 root root  4096 Feb  5 13:03 ..
-rwxrwxrwx 1 root root  1458 Aug 14 19:23 AU_place_checker.rb
-rwxrwxrwx 1 root root 11255 Aug 14 19:23 basic.rb
-rwxrwxrwx 1 root root  5634 Aug 14 19:23 BR_area_codes_checker.rb
-rwxrwxrwx 1 root root  2097 Aug 14 19:23 BR_soccer_teams_checker.rb
-rwxrwxrwx 1 root root  5184 Aug 14 19:23 date_checker.rb
-rwxrwxrwx 1 root root   571 Aug 14 19:23 DE_colour_checker.rb
-rwxrwxrwx 1 root root  1063 Aug 14 19:23 DE_emotion_checker.rb
-rwxrwxrwx 1 root root  1338 Aug 14 19:23 DE_family_checker.rb
-rwxrwxrwx 1 root root  1739 Aug 14 19:23 DE_religion_checker.rb
-rwxrwxrwx 1 root root   798 Aug 14 19:23 DE_road_checker.rb
-rwxrwxrwx 1 root root   363 Aug 14 19:23 DE_season_checker.rb
-rwxrwxrwx 1 root root   818 Aug 14 19:23 DE_sport_checker.rb
-rwxrwxrwx 1 root root  1262 Aug 14 19:23 DE_vehicle_checker.rb
-rwxrwxrwx 1 root root  4823 Aug 14 19:23 email_names.rb
-rwxrwxrwx 1 root root   510 Aug 14 19:23 EN_colour_checker.rb
-rwxrwxrwx 1 root root  1088 Aug 14 19:23 EN_emotion_checker.rb
-rwxrwxrwx 1 root root  1476 Aug 14 19:23 EN_explicit_checker.rb
-rwxrwxrwx 1 root root  1391 Aug 14 19:23 EN_family_checker.rb
-rwxrwxrwx 1 root root  1181 Aug 14 19:23 EN_military_checker.rb
-rwxrwxrwx 1 root root  1625 Aug 14 19:23 EN_religion_checker.rb
-rwxrwxrwx 1 root root   804 Aug 14 19:23 EN_road_checker.rb
-rwxrwxrwx 1 root root   329 Aug 14 19:23 EN_season_checker.rb
-rwxrwxrwx 1 root root   825 Aug 14 19:23 EN_sport_checker.rb
-rwxrwxrwx 1 root root   758 Aug 14 19:23 EN_vehicle_checker.rb
-rwxrwxrwx 1 root root   757 Aug 14 19:23 EN_violence_checker.rb
-rwxrwxrwx 1 root root  1949 Aug 14 19:23 external_list_checker.rb
-rwxrwxrwx 1 root root  6100 Aug 14 19:23 FR_area_codes.rb
-rwxrwxrwx 1 root root   501 Aug 14 19:23 FR_colour_checker.rb
-rwxrwxrwx 1 root root  4409 Aug 14 19:23 FR_date_checker.rb
-rwxrwxrwx 1 root root  1942 Aug 14 19:23 FR_emotion_checker.rb
-rwxrwxrwx 1 root root  3064 Aug 14 19:23 frequency.rb
-rwxrwxrwx 1 root root  1292 Aug 14 19:23 FR_family_checker.rb
-rwxrwxrwx 1 root root  1461 Aug 14 19:23 FR_hashcat_mask_generator.rb
-rwxrwxrwx 1 root root   342 Aug 14 19:23 FR_season_checker.rb
-rwxrwxrwx 1 root root   725 Aug 14 19:23 FR_windows_complexity_checker.rb
-rwxrwxrwx 1 root root  1854 Aug 14 19:23 hashcat_mask_generator.rb
-rwxrwxrwx 1 root root   446 Aug 14 19:23 NL_colour_checker.rb
-rwxrwxrwx 1 root root  3516 Aug 14 19:23 NL_date_checker.rb
-rwxrwxrwx 1 root root   356 Aug 14 19:23 NL_season_checker.rb
-rwxrwxrwx 1 root root   596 Aug 14 19:23 PTBR_colour_checker.rb
-rwxrwxrwx 1 root root  3645 Aug 14 19:23 PTBR_date_checker.rb
-rwxrwxrwx 1 root root  4963 Aug 14 19:23 PTBR_emotion_checker.rb
-rwxrwxrwx 1 root root  3204 Aug 14 19:23 PTBR_explicit_checker.rb
-rwxrwxrwx 1 root root  1423 Aug 14 19:23 PTBR_family_checker.rb
-rwxrwxrwx 1 root root  2421 Aug 14 19:23 PTBR_religion_checker.rb
-rwxrwxrwx 1 root root   408 Aug 14 19:23 PTBR_season_checker.rb
-rwxrwxrwx 1 root root  6328 Aug 14 19:23 RU_russia_cities_checker.rb
-rwxrwxrwx 1 root root  1000 Aug 14 19:23 special_checker.rb
-rwxrwxrwx 1 root root 27090 Aug 14 19:23 US_area_codes_checker.rb
-rwxrwxrwx 1 root root  3359 Aug 14 19:23 usernames.rb
-rwxrwxrwx 1 root root  2225 Aug 14 19:23 US_state_checker.rb
-rwxrwxrwx 1 root root  3097 Aug 14 19:23 US_zip_codes_checker.rb
-rwxrwxrwx 1 root root   682 Aug 14 19:23 windows_complexity_checker.rb
`

**Comment by xkeksi** [comment]
also here: head, i forgot to add

root@20012-42031:~/test/checkers_enabled# head 01basic.rb
../checkers_available/basic.rbroot@20012-42031:~/test/checkers_enabled#

../checkers_available/basic.rbroot@20012-42031:~/test/checkers_enabled# head README
This directory contains the checkers you want to enable.

The way I see this working is the same as Apache does with modules and sites,
keep the checkers in the checkers_available directory but then symlink the
ones you want to use into here.

**Comment by digininja** [comment]
Can you repaste that with syntax wrapping as GitHub is messing with the
content. Use three backticks around the pasted bit so it comes in as
unmodified content.

**Comment by xkeksi** [comment]
```
root@20012-42031:~/test/checkers_enabled# head 01basic.rb
../checkers_available/basic.rb


---
root@20012-42031:~/test/checkers_enabled# head README
This directory contains the checkers you want to enable.

The way I see this working is the same as Apache does with modules and sites,
keep the checkers in the checkers_available directory but then symlink the
ones you want to use into here.


```

**Comment by digininja** [comment]
Your problem is that the file `01basic.rb` in checkers_enabled is a file with the contents `../checkers_available/basic.rb` rather than a symlink. Did you create that file yourself?

**Comment by xkeksi** [comment]
no

**Comment by xkeksi** [comment]
as ive said, i cloned the repo and didnt modify anything

**Comment by xkeksi** [comment]
So recently if you download the repo, unzipping it and then dragging it via ftp into your vserver breaks the syslink and it will throw that error

fix: just clone via git command and then everything should work fine 

git clone https://github.com/digininja/pipal

**Comment by digininja** [comment]
That is why the install instructions are there, they are a known good and
working way to install the tool.

Glad it's sorted though.
